Task 8
Viccart/CodePress-frontend pull request #6
Opened 2023-04-20 13:51 UTC by Viccart

2023-04-20 14:27 UTC, B7Bprog requested changes
Hey Hannah, I really like the design of your site.

Here are a few things to fix/refactor:

- The logged-in user should be indicated on each page.
- User should be able to use the form and post again after a comment had been posted. Without refreshing the page.
- An error message should be displayed when the post request is unsuccessful.
- The form should be disabled for the time of posting.

Please add these functionalities, then send us another PR with it.

2023-04-20 14:27 UTC, B7Bprog commented on src/components/AddComment.jsx
> +    console.log("form submitted");
Please remove all logs from this final code.

2023-04-21 09:11 UTC, callumu21 approved these changes
Really nice job implementing Béla's changes. I've left a couple of comments for minor changes, but this is good to merge now 👍 

As a minor bit of styling for later, you may want to resize the textarea for a comment body depending on the screen size, maybe keeping it in line with the comment cards for a consistent look on the page.

2023-04-21 09:11 UTC, callumu21 commented on src/api.js
> +  console.log(newComment);
This console.log should be removed

2023-04-21 09:11 UTC, callumu21 commented on src/components/AddComment.jsx
> +    setIsSubmitted(true);
I would rename this state to isSubmitting to illustrate you're tracking the progress of a submit, not whether a user has submitted successfully.

2023-04-21 09:15 UTC, merged